// examples/vue/src/components/Editor.vue
<script lang="ts" setup>
import { useEditor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { symbol } from '../../../..'

const editor = useEditor({
  content: '<p>@vueditor/tiptap-extension-symbol</p>',
  extensions: [
    StarterKit,
    symbol
  ],
})
</script>

<template>
  <div class="editor">
    <EditorContent :editor="editor" />
  </div>
</template>

<style lang="scss">
.editor {
  box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);

  .tiptap {
    padding: 24px 64px;

    &:focus-visible {
      outline: none;
    }
  }
}
</style>

// examples/react/src/Editor.tsx
import { EditorProvider } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { symbol } from '../../..'
import './Editor.scss'

// define your extension array
const extensions = [StarterKit, symbol.configure({
  enableId: false,
  enableName: true,
})]
const content = '@vueditor/tiptap-extension-symbol'

export default function Editor() {
  return (
    <div className="editor">
      <EditorProvider extensions={extensions} content={content}>

      </EditorProvider>
    </div>
  )
}
